-- Aquí iremos pegando las modificaciones que hagamos en la base de datos creando dos comentarios para acotar los cambios realizados para una nueva historia

-- INICIO Cambios para FG4-28 FECHA: 01-07-2022 13:40
-- creacion de tablas

CREATE TABLE CLIENT (
	ID INTEGER NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	SURNAME VARCHAR(150) NOT NULL,
	NIF CHAR(9) NOT NULL,
	BIRTH_DATE DATE,
	CONSTRAINT CLI_PK PRIMARY KEY (ID),
	CONSTRAINT CLI_CH CHECK (BIRTH_DATE > '1800-01-01')
);

CREATE TABLE TRANSACTIONS (
	SELLER_CLI INTEGER,
	BUYER_CLI INTEGER,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	PRICE FLOAT NOT NULL,
	PRODUCT_NAME VARCHAR(80) NOT NULL,
	PRODUCT_CATEGORY VARCHAR(80) NOT NULL,
	CONSTRAINT TRA_PK PRIMARY KEY (SELLER_CLI, BUYER_CLI),
	CONSTRAINT TRA_CLI1 FOREIGN KEY (SELLER_CLI) REFERENCES CLIENT(ID),
	CONSTRAINT TRA_CLI2 FOREIGN KEY (BUYER_CLI) REFERENCES CLIENT(ID)
);

-- insercion de datos

INSERT INTO PUBLIC.CLIENT VALUES (1, 'DONATO', 'RAMOS MARTINEZ', '92444802M', '1973-01-16');
INSERT INTO PUBLIC.CLIENT VALUES (2, 'JAVIER', 'FANDINO CASAL', '01275066S', '1989-09-16');
-- FIN cambios para FG4-28 FECHA: 01-07-2022 15:00

